# Generated by Django 4.0.4 on 2022-08-18 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название поста')),
                ('body', models.CharField(max_length=65536, verbose_name='Содержание поста')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Объект удален')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.category')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
