# Generated by Django 4.0.4 on 2022-08-21 10:39

from django.db import migrations, models
import django.utils.timezone
import post.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(blank=True, null=True, upload_to=post.models.post_file_name, verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Файл содержания поста',
                'verbose_name_plural': 'Файлы содержания поста',
            },
        ),
    ]
