# Generated by Django 4.0.4 on 2022-07-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timemodel')),
                ('source_name', models.CharField(max_length=32, unique=True, verbose_name='Название ресурса')),
                ('contact_value', models.CharField(max_length=32, verbose_name='Значение контакта')),
            ],
            bases=('core.timemodel',),
        ),
    ]
