# Generated by Django 4.0.4 on 2022-07-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
