# Generated by Django 4.0.4 on 2022-07-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('timemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timemodel')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название поста')),
                ('body', models.CharField(max_length=65536, verbose_name='Содержание поста')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Объект удален')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=('core.timemodel',),
        ),
    ]
