# Generated by Django 4.0.4 on 2022-07-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValueModel',
            new_name='KeyValue',
        ),
    ]
